version: '3'
services:
  magento:
    build: 
      context: '.'
    ports:
      - '${MAGENTO_HTTP_PORT}:80'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html/app/design/frontend/mytheme/default'
    environment:
      - MYSQL_HOST=mysql
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
volumes: {}
